# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libudunits2-dev
      - netcdf-bin
