---
title: "Tools for earthquake analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tools for earthquake analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction

This package handles the dataset about earthquakes provided by the [U.S. National Oceanographic and Atmospheric Administration (NOAA)](https://www.ngdc.noaa.gov/). It is made for educational purpose, as the final assignment of the Coursera MSDR Capstone project. 

# Install the package

```{r setup}
library(devtools)
install_github("BFavetto/EarthquakeAnalysis")
library(EarthquakeAnalysis)

library(ggplot2)
library(dplyr)
```

# Load and clean the NOAA dataset

```{r loadcleandata}
# to load the data from the package
data("NOAAdata")

dataclean1 <- eq_clean_data(NOAAdata)
View(dataclean1)
dataclean2 <- eq_location_clean(dataclean1)
View(dataclean2)
```


```{r}
dataclean2 %>% filter((Year > 2010) &  (Country =="INDIA")) %>%
ggplot(  aes(x = Date,
           y = Country,
           color = Deaths,
           size = Mag)) + geom_timeline(alpha = 0.2)
```

